// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeNest.Data;

#nullable disable

namespace TradeNest.Data.Migrations
{
    [DbContext(typeof(TradeNestDbContext))]
    [Migration("20260311063858_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradeNest.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("Holds User data.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("d05a8fe7-cf0a-4895-89aa-9068c334ec1b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "793361c8-6fb9-4f24-b9d9-a2026b65e404",
                            Email = "User1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEEx+YuzqgSVINQhuAhYoRTM1S5pqJPtB0+Aom9H/FtdRdHhei2HxBrgpWkOcJBJqkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a23d8472-0591-47d3-91ab-f6afcb3ee7fc",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = new Guid("a8e18a83-adfb-4116-9e35-3be16446f9b8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a210468d-afe9-41df-8dc8-a8e5d798f944",
                            Email = "User2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEDrJGKPOW1QrGI2LkJ6V1it4vpnjKR0rCQNTnjbwfuT6ST7EF8/JRCg93RCBd0BffA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12fdb501-2dea-4628-960e-a795725799e4",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Cart's primary key.");

                    b.Property<Guid>("CartOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("One to one relation with User. Dependant.");

                    b.HasKey("Id");

                    b.HasIndex("CartOwnerId")
                        .IsUnique();

                    b.ToTable("Carts", t =>
                        {
                            t.HasComment("Holds Cart data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.CartProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's primary key.");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the cart's primary key.");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETUTCDATE()")
                        .HasComment("The date and time that the product was added to the cart.");

                    b.Property<int>("ProductQuantityAdded")
                        .HasColumnType("int")
                        .HasComment("The value describes how much quantity of the given product is added in the given Cart.");

                    b.HasKey("ProductId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartsProducts", t =>
                        {
                            t.HasComment("Mapping entity between Cart and Products - represents product added to cart.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category's primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Category's name.");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("Holds category data.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6b3e6e0-3e3d-4c3d-8e7c-0b9a1b4e2f30"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("f0e9d8c7-b6a5-4321-fedc-ba9876543210"),
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7890-abcd-ef0123456789"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("9f8e7d6c-5b4a-3210-fedc-ba9876543210"),
                            Name = "Sporting Goods"
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Image's primary key");

                    b.Property<bool>("IsFrontImage")
                        .HasColumnType("bit")
                        .HasComment("Value represents weather the image is used as a front image for the product or not.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the image's product primary key.");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Image's Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images", t =>
                        {
                            t.HasComment("Holds Image data.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8dbe53a-fadc-4dfb-8b3a-e82f1334f052"),
                            IsFrontImage = true,
                            ProductId = new Guid("e5f6a7b8-c9d0-1234-5555-666677778888"),
                            Url = "/images/products/chair_angle_1.png"
                        },
                        new
                        {
                            Id = new Guid("25665742-f35f-4e0d-adba-c02f5eb7a444"),
                            IsFrontImage = false,
                            ProductId = new Guid("e5f6a7b8-c9d0-1234-5555-666677778888"),
                            Url = "/images/products/chair_angle_2.png"
                        },
                        new
                        {
                            Id = new Guid("75b8d9c0-a895-4856-893b-a5102952e284"),
                            IsFrontImage = false,
                            ProductId = new Guid("e5f6a7b8-c9d0-1234-5555-666677778888"),
                            Url = "/images/products/chair_angle_3.png"
                        },
                        new
                        {
                            Id = new Guid("f32e52d9-9f9c-416e-8567-e1c5502a9b1a"),
                            IsFrontImage = true,
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-1111-222233334444"),
                            Url = "/images/products/headphones.png"
                        },
                        new
                        {
                            Id = new Guid("b6a043db-7cba-4997-8a37-f794dccf7c4b"),
                            IsFrontImage = false,
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-1111-222233334444"),
                            Url = "/images/products/headphones_part_1.png"
                        },
                        new
                        {
                            Id = new Guid("d7089810-b52b-4a91-80f7-b7f41de2045e"),
                            IsFrontImage = false,
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-1111-222233334444"),
                            Url = "/images/products/headphones_part_2.png"
                        },
                        new
                        {
                            Id = new Guid("ccfb563e-bca5-4f0e-a55d-61d20bdf789f"),
                            IsFrontImage = false,
                            ProductId = new Guid("a1b2c3d4-e5f6-7890-1111-222233334444"),
                            Url = "/images/products/headphones_part_3.png"
                        },
                        new
                        {
                            Id = new Guid("b42f4a9e-51a3-4c84-ba33-f74f0a48d544"),
                            IsFrontImage = false,
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-2222-333344445555"),
                            Url = "/images/products/tv_part_1.png"
                        },
                        new
                        {
                            Id = new Guid("203a1575-d818-4ddc-97c0-05a850e53370"),
                            IsFrontImage = false,
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-2222-333344445555"),
                            Url = "/images/products/tv_part_2.png"
                        },
                        new
                        {
                            Id = new Guid("3c265bcb-bf21-4951-9ddd-438934e9686d"),
                            IsFrontImage = false,
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-2222-333344445555"),
                            Url = "/images/products/tv_part_3.png"
                        },
                        new
                        {
                            Id = new Guid("988c072b-dde1-43e3-bac1-04284a955fc6"),
                            IsFrontImage = true,
                            ProductId = new Guid("b2c3d4e5-f6a7-8901-2222-333344445555"),
                            Url = "/images/products/tv.png"
                        },
                        new
                        {
                            Id = new Guid("76384254-1606-4b50-86ae-cef4af3fb0aa"),
                            IsFrontImage = true,
                            ProductId = new Guid("f6a7b8c9-d0e1-2345-6666-777788889999"),
                            Url = "/images/products/succulents.png"
                        },
                        new
                        {
                            Id = new Guid("032b49cb-f302-4a5d-8aab-68225304e43e"),
                            IsFrontImage = true,
                            ProductId = new Guid("d4e5f6a7-b8c9-0123-4444-555566667777"),
                            Url = "/images/products/csharp_book.png"
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Order's primary key.");

                    b.Property<DateTime>("SubmittedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("The date and time at which the order has been submitted.");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Holds the value of the order's total price when order is submitted.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the user that has made the order.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Holds order's data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("OrderProduct primary key.");

                    b.Property<decimal?>("CostPriceAtOrderTime")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Represents the cost price of the product at the moment the order is submitted.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the Order's primary key.");

                    b.Property<Guid>("OriginalProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the original product primary key.");

                    b.Property<string>("ProductNameAtOrderTime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("The product name at the time that the order is submitted.");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasComment("Represents the quantity of the product that was ordered.");

                    b.Property<decimal>("TotalProductPriceAtOrderTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComputedColumnSql("[UnitSellingPriceAtOrderTime] * [QuantityOrdered]", true)
                        .HasComment("Computed and stored in a column from QuantityOrdered * UnitSellingPriceAtOrderTime.");

                    b.Property<decimal>("UnitSellingPriceAtOrderTime")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Represents the selling price of a unit of the product at the moment the order is submitted.");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OriginalProductId");

                    b.ToTable("OrdersProducts", t =>
                        {
                            t.HasComment("Represents the product state at the moment of the order being submitted.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product's primary key.");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's category primary key.");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("The price cost of attaining/producing the product. Is for user statistics. Nullable.");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Date of creating. Has default universal time set on record insertion to date and time of insertion.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasComment("Product's description.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Value is used to show weather the product deleted.");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Value is used to show weather the product is enabled or disabled for selling.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Product's name.");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's owner primary key.");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int")
                        .HasComment("The quantity of the product that is available in stock.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("The price the product is being sold at.");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("Holds product's data.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1111-222233334444"),
                            CategoryId = new Guid("c6b3e6e0-3e3d-4c3d-8e7c-0b9a1b4e2f30"),
                            CostPrice = 45.00m,
                            CreatedOn = new DateTime(2026, 3, 11, 6, 38, 57, 436, DateTimeKind.Utc).AddTicks(9577),
                            Description = "High-fidelity audio with noise-cancelling features and comfortable earcups for extended listening sessions. Up to 20 hours of battery life.",
                            IsDeleted = false,
                            IsEnabled = true,
                            Name = "Wireless Bluetooth Headphones",
                            OwnerId = new Guid("d05a8fe7-cf0a-4895-89aa-9068c334ec1b"),
                            QuantityInStock = 10,
                            SellingPrice = 99.99m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-2222-333344445555"),
                            CategoryId = new Guid("c6b3e6e0-3e3d-4c3d-8e7c-0b9a1b4e2f30"),
                            CostPrice = 300.00m,
                            CreatedOn = new DateTime(2026, 3, 11, 6, 38, 57, 436, DateTimeKind.Utc).AddTicks(9592),
                            Description = "4K Ultra HD Smart TV with vibrant colors and intelligent processing Built-in streaming apps for endless entertainment. Includes a voice remote.",
                            IsDeleted = false,
                            IsEnabled = true,
                            Name = "Smart LED TV 55-inch",
                            OwnerId = new Guid("d05a8fe7-cf0a-4895-89aa-9068c334ec1b"),
                            QuantityInStock = 5,
                            SellingPrice = 599.00m
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-4444-555566667777"),
                            CategoryId = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            CostPrice = 12.00m,
                            CreatedOn = new DateTime(2026, 3, 11, 6, 38, 57, 436, DateTimeKind.Utc).AddTicks(9596),
                            Description = "A comprehensive guide for beginners to learn C# programming language covering basics to advanced topics with practical examples and exercises.",
                            IsDeleted = false,
                            IsEnabled = true,
                            Name = "Introduction to C# Programming",
                            OwnerId = new Guid("a8e18a83-adfb-4116-9e35-3be16446f9b8"),
                            QuantityInStock = 20,
                            SellingPrice = 24.99m
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-5555-666677778888"),
                            CategoryId = new Guid("f0e9d8c7-b6a5-4321-fedc-ba9876543210"),
                            CostPrice = 80.00m,
                            CreatedOn = new DateTime(2025, 12, 26, 6, 38, 57, 436, DateTimeKind.Utc).AddTicks(9599),
                            Description = "Designed for maximum comfort and support during long working hours. Features adjustable lumbar support, armrests, and headrest.",
                            IsDeleted = false,
                            IsEnabled = true,
                            Name = "Ergonomic Office Chair",
                            OwnerId = new Guid("a8e18a83-adfb-4116-9e35-3be16446f9b8"),
                            QuantityInStock = 10,
                            SellingPrice = 179.99m
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-6666-777788889999"),
                            CategoryId = new Guid("f0e9d8c7-b6a5-4321-fedc-ba9876543210"),
                            CostPrice = 15.00m,
                            CreatedOn = new DateTime(2026, 2, 19, 6, 38, 57, 436, DateTimeKind.Utc).AddTicks(9606),
                            Description = "A beautiful collection of five low-maintenance succulent plants, perfect for decorating your home or office space. Comes with decorative pots.",
                            IsDeleted = false,
                            IsEnabled = true,
                            Name = "Indoor Plant Set - Succulents",
                            OwnerId = new Guid("a8e18a83-adfb-4116-9e35-3be16446f9b8"),
                            QuantityInStock = 30,
                            SellingPrice = 34.99m
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.UserWatchlistProduct", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the watchlist's owner primary key.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the watchlist's product primary key.");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UsersWatchlistsProducts", t =>
                        {
                            t.HasComment("Mapping entity representing a product in a user's watchlist.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "CartOwner")
                        .WithOne("Cart")
                        .HasForeignKey("TradeNest.Data.Models.Cart", "CartOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartOwner");
                });

            modelBuilder.Entity("TradeNest.Data.Models.CartProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("ProductCarts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Image", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeNest.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.Product", "OriginalProduct")
                        .WithMany("SoldProducts")
                        .HasForeignKey("OriginalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OriginalProduct");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Products")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TradeNest.Data.Models.UserWatchlistProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("ProductWatchlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "User")
                        .WithMany("WatchlistProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeNest.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("WatchlistProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductCarts");

                    b.Navigation("ProductWatchlists");

                    b.Navigation("SoldProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
