// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeNest.Data;

#nullable disable

namespace TradeNest.Data.Migrations
{
    [DbContext(typeof(TradeNestDbContext))]
    partial class TradeNestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradeNest.Data.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key of the admin entity.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the user that is an Admin.");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins", null, t =>
                        {
                            t.HasComment("Represents the Admin entity.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("Holds User data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Cart's primary key.");

                    b.Property<Guid>("CartOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("One to one relation with User. Dependant.");

                    b.HasKey("Id");

                    b.HasIndex("CartOwnerId")
                        .IsUnique();

                    b.ToTable("Carts", null, t =>
                        {
                            t.HasComment("Holds Cart data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.CartProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's primary key.");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the cart's primary key.");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("The date and time that the product was added to the cart.");

                    b.Property<int>("ProductQuantityAdded")
                        .HasColumnType("int")
                        .HasComment("The value describes how much quantity of the given product is added in the given Cart.");

                    b.HasKey("ProductId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartsProducts", null, t =>
                        {
                            t.HasComment("Mapping entity between Cart and Products - represents product added to cart.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Category's primary key.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Category's name.");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasComment("Holds category data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Image's primary key");

                    b.Property<bool>("IsFrontImage")
                        .HasColumnType("bit")
                        .HasComment("Value represents weather the image is used as a front image for the product or not.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the image's product primary key.");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Image's Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images", null, t =>
                        {
                            t.HasComment("Holds Image data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Order's primary key.");

                    b.Property<DateTime>("SubmittedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("The date and time at which the order has been submitted.");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Holds the value of the order's total price when order is submitted.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the user that has made the order.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasComment("Holds order's data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("OrderProduct primary key.");

                    b.Property<decimal?>("CostPriceAtOrderTime")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Represents the cost price of the product at the moment the order is submitted.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the Order's primary key.");

                    b.Property<Guid>("OriginalProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the original product primary key.");

                    b.Property<string>("ProductNameAtOrderTime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("The product name at the time that the order is submitted.");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasComment("Represents the quantity of the product that was ordered.");

                    b.Property<decimal>("TotalProductPriceAtOrderTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComputedColumnSql("[UnitSellingPriceAtOrderTime] * [QuantityOrdered]", true)
                        .HasComment("Computed and stored in a column from QuantityOrdered * UnitSellingPriceAtOrderTime.");

                    b.Property<decimal>("UnitSellingPriceAtOrderTime")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("Represents the selling price of a unit of the product at the moment the order is submitted.");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OriginalProductId");

                    b.ToTable("OrdersProducts", null, t =>
                        {
                            t.HasComment("Represents the product state at the moment of the order being submitted.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Product's primary key.");

                    b.Property<Guid?>("ApprovalDecisionMakerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the admin that has taken a decision on the product approval if any.");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's category primary key.");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("The price cost of attaining/producing the product. Is for user statistics. Nullable.");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Date of creating. Has default universal time set on record insertion to date and time of insertion.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasComment("Product's description.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Value is used to show weather the product deleted.");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Value is used to show weather the product is enabled or disabled for selling.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Product's name.");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the product's owner primary key.");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int")
                        .HasComment("The quantity of the product that is available in stock.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasComment("The price the product is being sold at.");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalDecisionMakerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Holds product's data.");
                        });
                });

            modelBuilder.Entity("TradeNest.Data.Models.UserWatchlistProduct", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the watchlist's owner primary key.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key referencing the watchlist's product primary key.");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UsersWatchlistsProducts", null, t =>
                        {
                            t.HasComment("Mapping entity representing a product in a user's watchlist.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradeNest.Data.Models.Admin", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("TradeNest.Data.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "CartOwner")
                        .WithOne("Cart")
                        .HasForeignKey("TradeNest.Data.Models.Cart", "CartOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartOwner");
                });

            modelBuilder.Entity("TradeNest.Data.Models.CartProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("ProductCarts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Image", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeNest.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.Product", "OriginalProduct")
                        .WithMany("SoldProducts")
                        .HasForeignKey("OriginalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OriginalProduct");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Admin", "ApprovalDecisionMaker")
                        .WithMany("ProductApprovalDecisionsGiven")
                        .HasForeignKey("ApprovalDecisionMakerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradeNest.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Products")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TradeNest.Data.Models.Product.ApprovalDecision#TradeNest.Data.Models.ApprovalDecision", "ApprovalDecision", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ApprovalStatus")
                                .HasColumnType("int")
                                .HasComment("Value representing weather that product has been approved or not or is still waiting for a decision.");

                            b1.Property<string>("DecisionJustification")
                                .HasMaxLength(3000)
                                .HasColumnType("nvarchar(3000)")
                                .HasComment("The justification for the taken decision on the product approval.");

                            b1.Property<DateTime?>("TimeOfDecision")
                                .HasColumnType("datetime2")
                                .HasComment("Value representing the time the ticket has been processed and assigned approval status.");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("ApprovalDecision")
                        .IsRequired();

                    b.Navigation("ApprovalDecisionMaker");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TradeNest.Data.Models.UserWatchlistProduct", b =>
                {
                    b.HasOne("TradeNest.Data.Models.Product", "Product")
                        .WithMany("ProductWatchlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNest.Data.Models.ApplicationUser", "User")
                        .WithMany("WatchlistProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Admin", b =>
                {
                    b.Navigation("ProductApprovalDecisionsGiven");
                });

            modelBuilder.Entity("TradeNest.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("WatchlistProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("TradeNest.Data.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductCarts");

                    b.Navigation("ProductWatchlists");

                    b.Navigation("SoldProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
